<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Orders\Queries\**" />
    <EmbeddedResource Remove="Features\Orders\Queries\**" />
    <None Remove="Features\Orders\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="8.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Luqma.Data\Luqma.Data.csproj" />
    <ProjectReference Include="..\Luqma.Infrastructure\Luqma.Infrastructure.csproj" />
    <ProjectReference Include="..\Luqma.Service\Luqma.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Bills\Commands\Validators\" />
    <Folder Include="Features\Carts\Queries\Validators\" />
    <Folder Include="Features\CategoryItems\Commands\" />
    <Folder Include="Features\Customers\Queries\" />
    <Folder Include="Features\MenuContains\Commands\NewFolder\" />
    <Folder Include="Features\Payments\Commands\Validators\" />
    <Folder Include="Features\Salaries\Commands\Validators\" />
  </ItemGroup>

</Project>
